services:
  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  edwin-backend:
    image: ghcr.io/ksulakshana02/edwin-api:main
    container_name: edwin-backend
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      db:
        condition: service_healthy

volumes:
  dbdata:
