services:
  edwin-db:
    image: mysql:latest
    restart: always
    env_file:
      - ./db/.env
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    volumes:
      - ./db/dbdata:/var/lib/mysql
    container_name: edwin-db
    networks:
      - edwin-network

  edwin-backend:
    build: .
    container_name: edwin-backend
    restart: always
    depends_on:
      edwin-db:
        condition: service_healthy
    networks:
      - edwin-network

  edwin-frontend:
    build: ../EDWin-web
    depends_on:
      - edwin-backend
    restart: always
    container_name: edwin-frontend
    networks:
      - edwin-network

  edwin-pma:
    build: ./phpmyadmin
    depends_on:
      edwin-db:
        condition: service_healthy
    env_file:
      - ./db/.env
    container_name: edwin-pma
    restart: always
    networks:
      - edwin-network
    volumes:
      - pma:/var/www/pma/html/

volumes:
  pma:

networks:
  edwin-network:
    driver: bridge
